SELECT CURRENT_DATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

CREATE TABLE msg (
    id INT,
    content VARCHAR(30),
    send_time DATETIME
    );

INSERT INTO msg VALUES (1, 'hello, tom.', CURRENT_TIMESTAMP());
INSERT INTO msg VALUES (2, 'hello, jerry.', NOW());
INSERT INTO msg VALUES (3, 'hello, iris.', NOW());

SELECT NOW();

SELECT SYSDATE();

SELECT id, content, DATE(send_time) FROM msg;

SELECT TIMEDIFF(TIME(send_time), TIME(NOW())) FROM msg;
SELECT *, TIMEDIFF(TIME(send_time), TIME(NOW())) FROM msg WHERE TIMEDIFF(TIME(send_time), TIME(NOW())) <= '-00:20:00';

SELECT * FROM msg WHERE DATE_ADD(send_time, INTERVAL 20 MINUTE) >= NOW();
SELECT * FROM msg WHERE DATE_SUB(NOW(), INTERVAL 30 MINUTE) <= send_time;

SELECT DATEDIFF(DATE_ADD('1999-12-31', INTERVAL 80 YEAR), CURDATE());

# 计算年龄
SELECT TIMESTAMPDIFF(YEAR, '1999-12-31', CURDATE());

SELECT DATEDIFF(CURDATE(), '1999-12-31');

SELECT CONCAT(ROUND(DATEDIFF(CURDATE(), '1999-12-31') / DATEDIFF(DATE_ADD('1999-12-31', INTERVAL 80 YEAR), '1999-12-31') * 100), '%');

SELECT YEAR(NOW()), MONTH(NOW()), DATE(NOW()), DAY(NOW());

SELECT UNIX_TIMESTAMP();
SELECT UNIX_TIMESTAMP('2018-1-1 10:22:12');

SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(), '%Y-%m-%d %H:%i:%s');

SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(), '%Y-%m-%d %T');











