servers:
  ipAddress: 192.168.0.1
  #  ip-address: 192.168.0.1
  port: 8080
  # 不超时
  timeout: -1

  serverTimeOut: 3
  #  dataSize: 10
  dataSize: 10MB



datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  password: "0103"