server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    #    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  jpa:
    properties:
      hibernate:
      hbm2ddl:
        auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      ddl-auto: update